
name: .NET Core

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
    - name: Restore
      run: dotnet tool restore
    - name: Build with dotnet
      run: dotnet build -c Release
    - name: Test with dotnet
      run: dotnet test --no-build -c Release tests

  package:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
    - name: Restore
      run: dotnet tool restore
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Setup Version Suffix
      shell: pwsh
      run: ./build.ps1
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nupkg-${{ matrix.runs-on }}
        path: ./bin/*.nupkg
    - name: Push to GitHub Feed
      continue-on-error: true
      shell: bash
      run: |
          for f in ./bin/*.nupkg
          do
            echo $f
            dotnet nuget push $f -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
          done
